# Generated by Django 5.2.1 on 2025-06-26 13:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KKiaPayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_tontiflex', models.CharField(help_text='Référence unique TontiFlex', max_length=50, unique=True)),
                ('reference_kkiapay', models.CharField(blank=True, help_text='Référence retournée par KKiaPay', max_length=100, null=True)),
                ('type_transaction', models.CharField(choices=[('adhesion_tontine', "Frais d'adhésion tontine"), ('cotisation_tontine', 'Cotisation tontine'), ('retrait_tontine', 'Retrait tontine'), ('frais_creation_epargne', 'Frais création compte épargne'), ('depot_epargne', 'Dépôt épargne'), ('retrait_epargne', 'Retrait épargne'), ('remboursement_pret', 'Remboursement prêt'), ('autre', 'Autre')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('success', 'Succès'), ('failed', 'Échec'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('numero_telephone', models.CharField(help_text='Numéro Mobile Money du payeur', max_length=20)),
                ('objet_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné (tontine, compte épargne, prêt, etc.)", null=True)),
                ('objet_type', models.CharField(blank=True, help_text="Type d'objet concerné (Tontine, SavingsAccount, Loan, etc.)", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('kkiapay_response', models.JSONField(blank=True, default=dict, help_text="Réponse complète de l'API KKiaPay")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkiapay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction KKiaPay',
                'verbose_name_plural': 'Transactions KKiaPay',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_kk_user_id_6e1e89_idx'), models.Index(fields=['reference_tontiflex'], name='payments_kk_referen_00a415_idx'), models.Index(fields=['reference_kkiapay'], name='payments_kk_referen_ad3aa2_idx'), models.Index(fields=['type_transaction', 'status'], name='payments_kk_type_tr_d0fc19_idx'), models.Index(fields=['created_at'], name='payments_kk_created_5348d5_idx')],
            },
        ),
    ]
