services:
  - type: web
    name: tontiflex-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tontiflex.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: KKIAPAY_SANDBOX
        value: False
      - key: KKIAPAY_PUBLIC_KEY
        sync: false
      - key: KKIAPAY_PRIVATE_KEY
        sync: false
      - key: KKIAPAY_SECRET_KEY
        sync: false
      - key: KKIAPAY_WEBHOOK_SECRET
        generateValue: true

databases:
  - name: tontiflex-db
    databaseName: tontiflex
    user: tontiflex_user
