# Generated by Django 5.2.1 on 2025-06-21 09:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mobile_money', '0001_initial'),
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.AutoField(help_text='Identifiant unique de la cotisation', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la cotisation en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('date_cotisation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la cotisation')),
                ('numero_transaction', models.CharField(help_text='Numéro de transaction Mobile Money', max_length=255, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmee', 'Confirmée'), ('rejetee', 'Rejetée')], default='pending', help_text='Statut de la cotisation', max_length=20)),
                ('client', models.ForeignKey(help_text='Client ayant effectué la cotisation', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='accounts.client')),
                ('tontine', models.ForeignKey(help_text='Tontine concernée par cette cotisation', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='tontines.tontine')),
                ('transaction_mobile_money', models.ForeignKey(blank=True, help_text='Transaction Mobile Money associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_associees', to='mobile_money.transactionmobilemoney')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'db_table': 'tontines_cotisation',
                'ordering': ['-date_cotisation'],
                'indexes': [models.Index(fields=['tontine', 'client'], name='tontines_co_tontine_742200_idx'), models.Index(fields=['date_cotisation'], name='tontines_co_date_co_ce7df3_idx'), models.Index(fields=['statut'], name='tontines_co_statut_eb44c6_idx'), models.Index(fields=['numero_transaction'], name='tontines_co_numero__723539_idx')],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du retrait', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant demandé pour le retrait en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('date_demande_retrait', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la demande de retrait')),
                ('date_validation_retrait', models.DateTimeField(blank=True, help_text="Date et heure de validation du retrait par l'agent", null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('confirmee', 'Confirmé')], default='pending', help_text='Statut de la demande de retrait', max_length=20)),
                ('commentaires_agent', models.TextField(blank=True, help_text="Commentaires de l'agent lors de la validation")),
                ('raison_rejet', models.TextField(blank=True, help_text='Raison du rejet du retrait')),
                ('agent_validateur', models.ForeignKey(blank=True, help_text='Agent SFD ayant validé/rejeté le retrait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_valides', to='accounts.agentsfd')),
                ('client', models.ForeignKey(help_text='Client demandant le retrait', on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='accounts.client')),
                ('tontine', models.ForeignKey(help_text='Tontine concernée par ce retrait', on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='tontines.tontine')),
                ('transaction_mobile_money', models.ForeignKey(blank=True, help_text='Transaction Mobile Money de versement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_associes', to='mobile_money.transactionmobilemoney')),
            ],
            options={
                'verbose_name': 'Retrait',
                'verbose_name_plural': 'Retraits',
                'db_table': 'tontines_retrait',
                'ordering': ['-date_demande_retrait'],
                'indexes': [models.Index(fields=['tontine', 'client'], name='tontines_re_tontine_9dbdf5_idx'), models.Index(fields=['date_demande_retrait'], name='tontines_re_date_de_86c60f_idx'), models.Index(fields=['statut'], name='tontines_re_statut_81b45d_idx'), models.Index(fields=['agent_validateur'], name='tontines_re_agent_v_d0471f_idx')],
            },
        ),
    ]
