# Generated by Django 5.2.1 on 2025-06-21 11:43

import django.db.models.deletion
import tontines.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tontines', '0002_cotisation_retrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_debut', models.DateField(help_text='Date de début du cycle 31 jours')),
                ('mises_cochees', models.JSONField(default=tontines.models.default_mises_carnet, help_text='Liste de 31 booleans représentant les mises cochées (jour 1 à 31)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du carnet')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('client', models.ForeignKey(help_text='Client propriétaire du carnet', on_delete=django.db.models.deletion.CASCADE, related_name='carnets_cotisation', to='accounts.client')),
                ('tontine', models.ForeignKey(help_text='Tontine concernée', on_delete=django.db.models.deletion.CASCADE, related_name='carnets_cotisation', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Carnet Cotisation',
                'verbose_name_plural': 'Carnets Cotisation',
                'db_table': 'tontines_carnet_cotisation',
                'indexes': [models.Index(fields=['client', 'tontine', 'cycle_debut'], name='tontines_ca_client__9903bf_idx')],
                'unique_together': {('client', 'tontine', 'cycle_debut')},
            },
        ),
        migrations.CreateModel(
            name='SoldeTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde du client dans cette tontine (hors commissions SFD)', max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du solde')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('client', models.ForeignKey(help_text='Client propriétaire du solde', on_delete=django.db.models.deletion.CASCADE, related_name='soldes_tontines', to='accounts.client')),
                ('tontine', models.ForeignKey(help_text='Tontine concernée', on_delete=django.db.models.deletion.CASCADE, related_name='soldes_clients', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Solde Tontine',
                'verbose_name_plural': 'Soldes Tontines',
                'db_table': 'tontines_solde_tontine',
                'indexes': [models.Index(fields=['client', 'tontine'], name='tontines_so_client__8c4d6d_idx')],
                'unique_together': {('client', 'tontine')},
            },
        ),
    ]
