# Generated by Django 5.2.1 on 2025-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmobilemoney',
            name='is_commission',
            field=models.BooleanField(default=False, help_text='True si cette transaction est une commission SFD (première mise de cycle)'),
        ),
    ]
