# Generated by Django 5.2.1 on 2025-06-28 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('canal', models.CharField(choices=[('app', 'Application'), ('email', 'Email')], default='app', max_length=10, verbose_name='Canal')),
                ('envoye', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Liste des actions disponibles sous forme de boutons', verbose_name='Actions')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'core_notification',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date_creation'], name='core_notifi_utilisa_221d84_idx'), models.Index(fields=['canal'], name='core_notifi_canal_8e1fa7_idx')],
            },
        ),
    ]
